baseurl = "/"
languageCode = "en-gb"
languageLang = "en-gb"
title = "NeoSki"
enableRobotsTXT = true
[taxonomies]
  tag = 'tags'
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true